# Change these first
owner: sw-status-poc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites: # List of endpoints to track
  - name: Shipwire Website
    url: https://www.shipwire.com
  - name: Merchant
    url: https://merchant.shipwire.com
  - name: Admiral
    url: https://admiral.shipwire.com
  - name: Failing site
    url: http://uptimepoc.dev.gcp.shipwire.com
    
assignees: # Users to assign downtime issues (optional)
  - sw-status-poc
status-website:
  baseUrl: /status # where "repo" is your repository name
  name: swpocstats

