# Change these first
owner: sw-status-poc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
  - name: Paradojo
    url: https://paradojo.com
  - name: uptimepoc
    url: http://uptimepoc.dev.gcp.shipwire.com
    
assignees: # Users to assign downtime issues (optional)
  - sw-status-poc
status-website:
  baseUrl: /status # where "repo" is your repository name
  name: swpocstats
