# Change these first
owner: sw-status-poc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites: # List of endpoints to track
  - name: Shipwire Website
    url: https://www.shipwire.com
  - name: Merchant
    url: https://merchant.shipwire.com
  - name: Admiral
    url: https://admiral.shipwire.com
  - name: Failing site
    url: http://uptimepoc.dev.gcp.shipwire.com
  - name: WIAB
    url: https://app.shipwire.com/exec/report_mod/login.php
  - name: Confluence
    url: https://confluence.corp.shipwire.com/login.action
  - name: Jira
    url: https://issues.corp.shipwire.com
    
assignees: # Users to assign downtime issues (optional)
  - sw-status-poc
status-website:
  baseUrl: /status # where "repo" is your repository name
  name: Services Status
  logoUrl: https://www.shipwire.com/wp-content/themes/shipwire/assets/img/Shipwire_CEVA_Logo_Blk_2x.png
  favicon: https://dka575ofm4ao0.cloudfront.net/pages-favicon_logos/original/336/33QHgcyvQ4WPaI4au2RO

