# Change these first
owner: sw-status-poc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites: # List of endpoints to track
  - name: Shipwire Website
    url: https://www.shipwire.com
  - name: Merchant
    url: https://merchant.shipwire.com
  - name: Admiral
    url: https://admiral.shipwire.com
  - name: Failing site
    url: http://uptimepoc.dev.gcp.shipwire.com
    
assignees: # Users to assign downtime issues (optional)
  - sw-status-poc
status-website:
  baseUrl: /status # where "repo" is your repository name
  name: Shipwire Services Status
  logoUrl: https://www.shipwire.com/wp-content/themes/shipwire/assets/img/Shipwire_CEVA_Logo_Blk_2x.png

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
